services:
  - type: web
    name: mailbot
    runtime: python
    plan: free
    region: singapore
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        value: 8483045344:AAHvh-rpQIJpw6bBfrMC3UNjaH7bdYPAaUQ
      - key: PORT
        value: 10000
